

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: t47-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  tls:
  - hosts:
    - api47.my-points.ru
    - web47.my-points.ru
    - insights47.my-points.ru
    secretName: serverpod-tls-t47
  rules:
  - host: "api47.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t47-server-service
            port:
              name: api
  - host: "web47.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t47-server-service
            port:
              name: web
  - host: "insights47.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t47-server-service
            port:
              name: insights
    